<?php
namespace Mageplaza\GiftCard\Block\Adminhtml\Code\Edit\Tab;

class Code extends \Magento\Backend\Block\Widget\Form\Generic implements \Magento\Backend\Block\Widget\Tab\TabInterface
{
    protected $helperData;
    protected $_giftcardFactory;
    public function __construct(
        \Magento\Backend\Block\Template\Context $context,
        \Magento\Framework\Registry $registry,
        \Magento\Framework\Data\FormFactory $formFactory,
        \Mageplaza\GiftCard\Helper\Data $helperData,
        \Mageplaza\GiftCard\Model\GiftCardFactory $giftCardFactory,
        array $data = [])
    {
        $this->helperData = $helperData->getConfigValue('giftcard/code/code_length');
        $this->_giftcardFactory = $giftCardFactory;
        parent::__construct($context, $registry, $formFactory, $data);
    }

    protected function _prepareForm()
    {
        $form = $this->_formFactory->create();

        $fieldset = $form->addFieldset('base_fieldset', ['legend' => __('Giftcard Info')]);
        $dataUrl = $this->getRequest()->getParams();

//        echo '<pre>';
//        var_dump($dataUrl);
//        var_dump($this->getData('action'));
//        echo '</pre>';
//        die('1234');

        if (!isset($dataUrl['id'])){
//        Form create new
            $fieldset->addField(
                'giftcard_code_length',
                'text',
                [
                    'name' => 'code_length',
                    'label' => 'Code Length',
                    'title' => 'Code Length',
                ]
            );
            $fieldset->addField(
                'giftcard_balance',
                'text',
                [
                    'name' => 'balance',
                    'label' => 'Balance',
                    'title' => 'Balance',
//                'class' => 'required-entry'
                    'required' => true
                ]
            );
            $form->addValues([
                // id of input => value
                'giftcard_code_length' => $this->helperData
            ]);
        } else {
//        Form Edit
            $giftcard = $this->_giftcardFactory->create()->load($dataUrl['id'])->getData();

//            echo '<pre>';
//            var_dump($giftcard);
//            echo '</pre>';

            $fieldset->addField(
                'giftcard_id',
                'hidden',
                [
                    'name' => 'giftcard_id'
                ]
            );

            $fieldset->addField(
                'giftcard_code',
                'text',
                [
                    'name' => 'code',
                    'label' => 'Code',
                    'disabled' => true
                ]
            );
            $fieldset->addField(
                'giftcard_balance',
                'text',
                [
                    'name' => 'balance',
                    'label' => 'Balance'
                ]
            );
            $fieldset->addField(
                'giftcard_create_from',
                'text',
                [
                    'name' => 'create_from',
                    'label' => 'Create from',
                    'disabled' => true
                ]
            );
            $form->addValues([
                'giftcard_id' => $dataUrl['id'],
                'giftcard_code' => $giftcard['code'],
                'giftcard_balance' => $giftcard['balance'],
                'giftcard_create_from' => $giftcard['create_from']
            ]);
        }

        $this->setForm($form);
        return parent::_prepareForm(); // TODO: Change the autogenerated stub
    }

    public function getTabLabel()
    {
        // TODO: Implement getTabLabel() method.
        return __('gift card information');
    }

    public function getTabTitle()
    {
        // TODO: Implement getTabTitle() method.
        return $this->getTabLabel();
    }

    public function canShowTab()
    {
        // TODO: Implement canShowTab() method.
        return true;
//        return false;
    }

    public function isHidden()
    {
        // TODO: Implement isHidden() method.
        return false;
//        return true;
    }
}